version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'pgres'
      POSTGRES_PASSWORD: 'pgres'
      POSTGRES_DB: 'mydatabase'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./k8s-web-hello
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db

  goapp:
    build: ./go-microservice
    ports:
      - '8080:8080'
    depends_on:
      - db
      
  nginx:
    build: ./client
    ports:
      - '80:80'

volumes:
  postgres_data:
